### ISSUE TITLE
IfcLocalPlacement

### ISSUE THREAD

**Issue by carlopav** [yorikvanhavre/FreeCAD-NativeIFC#14]
This is another point i'd like to understand: @Moult how much is local placement used generally in Ifcs out there?

reading from Geometry use definitions, ref. https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcgeometricconstraintresource/lexical/ifclocalplacement.htm there are conventions like:

- IfcSite shall be placed absolutely within the world coordinate system established by the geometric representation context of the IfcProject
- IfcBuilding shall be placed relative to the local placement of IfcSite
- IfcBuildingStorey shall be placed relative to the local placement of IfcBuilding

In FreeCAD we have objects that can perfectly represent this @yorikvanhavre . I know we already discussed that in the past and we had different positions, should we adopt GeoFeatureGroups (Building, storey) or ShapeGroups (site) when IfcLocalPlacement is used? I think so, but what do you think?

**Comment by Moult** [comment]
Local placement is used in the vast majority of cases. However, it is not necessary to mirror this relative placement in FreeCAD - it gets resolved automatically via the IfcOpenShell API (you tell it where it should be in absolute coordinates, and it works out the relative placement automatically).

**Comment by carlopav** [comment]
I Imagine It was not necessary (this Is neither implemented in Arch wb), but looked reasonable to me to have the same behavior in FC and IFC, expecially when object editing will be possibile...

**Comment by Moult** [comment]
There are two things the user is interested in: the object placement (which in turn becomes the object insertion origin and pivot point for transformations), and the "parent" in the spatial hierarchy (container, aggregate, nested host, etc). As long as both are represented somehow (e.g. the former by the FreeCAD object origin and the latter by the hierarchy tree or a property dialog or similar) I think that is sufficient.

**Comment by carlopav** [comment]
Ok, it makes sense. Let's go for less mechanical-assebly flavour!
