### ISSUE TITLE
wrong method call in ifctools

### ISSUE THREAD

**Issue by berndhahnebach** [yorikvanhavre/FreeCAD-NativeIFC#20]
https://github.com/yorikvanhavre/FreeCAD-NativeIFC/blob/dcdcb49cf763c60944757b8dfe6be886429afbb3/ifc_tools.py#L627

see https://forum.freecad.org/viewtopic.php?t=72345&start=110#p661437

**Comment by berndhahnebach** [comment]
https://github.com/yorikvanhavre/FreeCAD-NativeIFC/pull/22

**Comment by yorikvanhavre** [comment]
Fixed by #22
