### ISSUE TITLE
Add ifcopenshell to FreeCAD Addon Manager's ALLOWED_PYTHON_PACKAGES.txt

### ISSUE THREAD

**Issue by luzpaz** [yorikvanhavre/FreeCAD-NativeIFC#3]
Add ifcoopenshell as a permitted dependency that the addon manager can auto-download.

**Comment by yorikvanhavre** [comment]
Is ifcopenshell installable that way? I haven ´t tested...

**Comment by Moult** [comment]
If it helps IOS is now available via pip, conda, docker, or manual download: https://blenderbim.org/docs-python/ifcopenshell-python/installation.html

**Comment by chennes** [comment]
Thanks @Moult -- added it to the allowed packages list in https://github.com/FreeCAD/FreeCAD-addons/commit/3e83af6b80e6a12dc5fd8ed68a7162a177d9bf35

**Comment by luzpaz** [comment]
ifcopenshell is not getting downloaded per user in the forum thread: https://forum.freecadweb.org/viewtopic.php?p=635336#p635336

**Comment by yorikvanhavre** [comment]
I added pip instructions to https://wiki.freecadweb.org/IfcOpenShell
I'll try to test installing it from the addon manager...

**Comment by yorikvanhavre** [comment]
Tested and everything is now working fine... I think we can close this then!
