### ISSUE TITLE
Allow to change the IFC schema

### ISSUE THREAD

**Issue by yorikvanhavre** [yorikvanhavre/FreeCAD-NativeIFC#35]
* query available schemas from ifcopenshell
* add a drop-down list to IFC_documents
* add function to change the schema - see https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/patch/operator.py

**Comment by yorikvanhavre** [comment]
@Moult @aothms is there a way to obtain from Python a list of IFC schemas supported by an instance of IfcOpenShell? Couldn't figure out...

**Comment by Moult** [comment]
`ifcopenshell.ifcopenshell_wrapper.schema_names()`

**Comment by yorikvanhavre** [comment]
Hah under my nose as usual :sweat_smile: Thanks!!!

**Comment by yorikvanhavre** [comment]
Using ifcopenshell.util.schema.Migrator: https://community.osarch.org/discussion/325/new-ifcopenshell-utility-to-convert-between-ifc2x3-and-ifc4

**Comment by yorikvanhavre** [comment]
As per https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcpatch/ifcpatch/recipes/Migrate.py#L46-L49 :

```python
file_patched = ifcopenshell.file(schema=newschema)
migrator = ifcopenshell.util.schema.Migrator()
for element in ifcfile:
    migrator.migrate(element, file_patched)
```
