### ISSUE TITLE
[Issue] Lock an unlocked file with more then one IfcProject inside

### ISSUE THREAD

**Issue by balrobs** [yorikvanhavre/FreeCAD-NativeIFC#63]
Steps to reproduce:

1. Start FreeCAD
2. File->New
3. File->Import [IfcProject_01.ifc.txt](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/files/14724993/IfcProject_01.ifc.txt) (with Native (ifc_import)
4. File->Import [IfcProject_02.ifc.txt](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/files/14724995/IfcProject_02.ifc.txt) (with Native (ifc_import)
5. Select BIM workbench
6. Notice that Strict IFC mode is OFF
![pic_01](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/assets/73989799/6707b756-9451-4cfb-8e90-cafa21d5085f)
7. Try to turn it ON by clicking it
![pic_02](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/assets/73989799/c4eb3e74-9b29-4592-b1f5-787efee99665)
8. Notice the status of the lock icon saying the document is locked while the message in the Report view saying the document can't be locked

**Comment by yorikvanhavre** [comment]
Thanks for notifying! Should be fixed now

**Comment by balrobs** [comment]
Problem fixed!
