### ISSUE TITLE
new name?

### ISSUE THREAD

**Issue by yorikvanhavre** [yorikvanhavre/FreeCAD-NativeIFC#9]
"BlenderBIM workbench" is not a very good name. What about "IFC workbench" or "nativeIFC"?

Not sure it will have a workbench, though. I think we could simply seamlessly integrate it to the BIM workbench, so BIM tools become nativeIFC-aware...

**Comment by paullee0** [comment]
Indeed :-

Native IFC
Native IFC Editing
... ?

**Comment by yorikvanhavre** [comment]
I think FreeCAD-NativeIFC for this repo, and we should use ifc_ prefix in the code instead of bb_ seems good...

**Comment by luzpaz** [comment]
The addon manager should display it as NativeIFC addon

**Comment by yorikvanhavre** [comment]
Done!
